[default]
time_to_remind = '30min'
log_level = 'debug'

[default.linear]
api_key = 'insert-here'
signing_key = 'insert-here'
target_status = 'Merged'
message = 'If this issue is QA-able, please write instructions and move to `QA Ready`. If not, mark it as `Done`. Thanks!\n\n*This is an automated message.*'
